name: ${project.name}
version: ${project.version}
main: "uk.co.jacekk.bukkit.bloodmoon.BloodMoon"
load: STARTUP
api-version: ${project.apiversion}

permissions:
  bloodmoon.reload:
      description: Allows the player to reload the config files