name: "${project.name}"
version: "${project.version}"
main: "uk.co.jacekk.bukkit.bloodmoon.BloodMoon"
load: STARTUP
api-version: 1.15

permissions:
  bloodmoon.reload:
      description: Allows the player to reload the config files